from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)

import poster

class Ui_tela_principal_1(object):
    def setupUi(self, tela_principal_1):
        if not tela_principal_1.objectName():
            tela_principal_1.setObjectName(u"tela_principal_1")
        tela_principal_1.resize(1075, 525)
        self.tela_principal_2 = QFrame(tela_principal_1)
        self.tela_principal_2.setObjectName(u"tela_principal_2")
        self.tela_principal_2.setGeometry(QRect(30, 10, 1031, 501))
        self.tela_principal_2.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.tela_principal_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.tela_principal_2.setFrameShadow(QFrame.Shadow.Raised)
        self.inicial = QFrame(self.tela_principal_2)
        self.inicial.setObjectName(u"inicial")
        self.inicial.setGeometry(QRect(0, 0, 1031, 51))
        self.inicial.setStyleSheet(u"background-color: rgb(34, 31, 31);")
        self.inicial.setFrameShape(QFrame.Shape.StyledPanel)
        self.inicial.setFrameShadow(QFrame.Shadow.Raised)
        self.btn_Cine_filme = QLabel(self.inicial)
        self.btn_Cine_filme.setObjectName(u"btn_Cine_filme")
        self.btn_Cine_filme.setGeometry(QRect(10, 10, 161, 41))
        self.btn_Cine_filme.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 900 22pt \"Segoe UI\";")
        self.btn_icon_perfil = QLabel(self.inicial)
        self.btn_icon_perfil.setObjectName(u"btn_icon_perfil")
        self.btn_icon_perfil.setGeometry(QRect(990, 10, 27, 27))
        self.btn_icon_perfil.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.btn_icon_perfil.setPixmap(QPixmap(u":/icon/icon_perfil.png"))
        self.btn_icon_perfil.setScaledContents(True)
        self.btn_Filmes_e_Series = QPushButton(self.inicial)
        self.btn_Filmes_e_Series.setObjectName(u"btn_Filmes_e_Series")
        self.btn_Filmes_e_Series.setGeometry(QRect(320, 20, 101, 24))
        self.btn_Filmes_e_Series.setStyleSheet(u"color: rgb(0, 255, 0);\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(34, 31, 31);")
        self.btn_Recomendacao_aleatorio = QPushButton(self.inicial)
        self.btn_Recomendacao_aleatorio.setObjectName(u"btn_Recomendacao_aleatorio")
        self.btn_Recomendacao_aleatorio.setGeometry(QRect(440, 20, 171, 24))
        self.btn_Recomendacao_aleatorio.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.btn_Inicio = QPushButton(self.inicial)
        self.btn_Inicio.setObjectName(u"btn_Inicio")
        self.btn_Inicio.setGeometry(QRect(200, 20, 101, 24))
        self.btn_Inicio.setStyleSheet(u"color: rgb(0, 255, 0);\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(34, 31, 31);")
        self.btn_Recomendacao_aleatorio.raise_()
        self.btn_icon_perfil.raise_()
        self.btn_Cine_filme.raise_()
        self.btn_Filmes_e_Series.raise_()
        self.btn_Inicio.raise_()
        self.btn_Star_wars = QLabel(self.tela_principal_2)
        self.btn_Star_wars.setObjectName(u"btn_Star_wars")
        self.btn_Star_wars.setGeometry(QRect(10, 140, 81, 121))
        self.btn_Star_wars.setPixmap(QPixmap(u":/icon/star wars.webp"))
        self.btn_Star_wars.setScaledContents(True)
        self.btn_Whicked = QLabel(self.tela_principal_2)
        self.btn_Whicked.setObjectName(u"btn_Whicked")
        self.btn_Whicked.setGeometry(QRect(110, 140, 81, 121))
        self.btn_Whicked.setPixmap(QPixmap(u":/icon/btn_img_wicked.png"))
        self.btn_Whicked.setScaledContents(True)
        self.btn_Flow = QLabel(self.tela_principal_2)
        self.btn_Flow.setObjectName(u"btn_Flow")
        self.btn_Flow.setGeometry(QRect(218, 140, 81, 121))
        self.btn_Flow.setPixmap(QPixmap(u":/icon/flow.webp"))
        self.btn_Flow.setScaledContents(True)
        self.btn_Ainda_estou_aqui = QLabel(self.tela_principal_2)
        self.btn_Ainda_estou_aqui.setObjectName(u"btn_Ainda_estou_aqui")
        self.btn_Ainda_estou_aqui.setGeometry(QRect(320, 140, 81, 121))
        self.btn_Ainda_estou_aqui.setPixmap(QPixmap(u":/icon/Ainda_Estou_Aqui.jpg"))
        self.btn_Ainda_estou_aqui.setScaledContents(True)
        self.btn_Robo_Selvagem = QLabel(self.tela_principal_2)
        self.btn_Robo_Selvagem.setObjectName(u"btn_Robo_Selvagem")
        self.btn_Robo_Selvagem.setGeometry(QRect(420, 140, 81, 121))
        self.btn_Robo_Selvagem.setPixmap(QPixmap(u":/icon/robo.jpg"))
        self.btn_Robo_Selvagem.setScaledContents(True)
        self.btn_Avengers = QLabel(self.tela_principal_2)
        self.btn_Avengers.setObjectName(u"btn_Avengers")
        self.btn_Avengers.setGeometry(QRect(520, 140, 81, 121))
        self.btn_Avengers.setPixmap(QPixmap(u":/icon/avengers.jpg"))
        self.btn_Avengers.setScaledContents(True)
        self.btn_Diverdida_mente_2 = QLabel(self.tela_principal_2)
        self.btn_Diverdida_mente_2.setObjectName(u"btn_Diverdida_mente_2")
        self.btn_Diverdida_mente_2.setGeometry(QRect(620, 140, 81, 121))
        self.btn_Diverdida_mente_2.setPixmap(QPixmap(u":/icon/disney.jpeg"))
        self.btn_Diverdida_mente_2.setScaledContents(True)
        self.btn_Jonh_Wick_3 = QLabel(self.tela_principal_2)
        self.btn_Jonh_Wick_3.setObjectName(u"btn_Jonh_Wick_3")
        self.btn_Jonh_Wick_3.setGeometry(QRect(720, 140, 91, 121))
        self.btn_Jonh_Wick_3.setPixmap(QPixmap(u":/icon/Jonh wick.jpg"))
        self.btn_Jonh_Wick_3.setScaledContents(True)
        self.btn_Duna_parte_2 = QLabel(self.tela_principal_2)
        self.btn_Duna_parte_2.setObjectName(u"btn_Duna_parte_2")
        self.btn_Duna_parte_2.setGeometry(QRect(840, 140, 81, 131))
        self.btn_Duna_parte_2.setPixmap(QPixmap(u":/icon/duna 2.webp"))
        self.btn_Duna_parte_2.setScaledContents(True)
        self.btn_One_Piece_2 = QLabel(self.tela_principal_2)
        self.btn_One_Piece_2.setObjectName(u"btn_One_Piece_2")
        self.btn_One_Piece_2.setGeometry(QRect(120, 310, 81, 141))
        self.btn_One_Piece_2.setPixmap(QPixmap(u":/icon/one piece red.jpg"))
        self.btn_One_Piece_2.setScaledContents(True)
        self.btn_Solteiro_em_seul = QLabel(self.tela_principal_2)
        self.btn_Solteiro_em_seul.setObjectName(u"btn_Solteiro_em_seul")
        self.btn_Solteiro_em_seul.setGeometry(QRect(10, 310, 91, 141))
        self.btn_Solteiro_em_seul.setPixmap(QPixmap(u":/icon/single in seul.jpg"))
        self.btn_Solteiro_em_seul.setScaledContents(True)
        self.btn_ghost_in_the_shell = QLabel(self.tela_principal_2)
        self.btn_ghost_in_the_shell.setObjectName(u"btn_ghost_in_the_shell")
        self.btn_ghost_in_the_shell.setGeometry(QRect(220, 310, 81, 141))
        self.btn_ghost_in_the_shell.setPixmap(QPixmap(u":/icon/ghost in the shell.jpg"))
        self.btn_ghost_in_the_shell.setScaledContents(True)
        self.btn_Gladiador_2 = QLabel(self.tela_principal_2)
        self.btn_Gladiador_2.setObjectName(u"btn_Gladiador_2")
        self.btn_Gladiador_2.setGeometry(QRect(320, 310, 81, 141))
        self.btn_Gladiador_2.setPixmap(QPixmap(u":/icon/Gladiador 2.webp"))
        self.btn_Gladiador_2.setScaledContents(True)
        self.btn_Senna = QLabel(self.tela_principal_2)
        self.btn_Senna.setObjectName(u"btn_Senna")
        self.btn_Senna.setGeometry(QRect(420, 310, 81, 141))
        self.btn_Senna.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_Senna.setPixmap(QPixmap(u":/icon/sena.webp"))
        self.btn_Senna.setScaledContents(True)
        self.btn_Substancia = QLabel(self.tela_principal_2)
        self.btn_Substancia.setObjectName(u"btn_Substancia")
        self.btn_Substancia.setGeometry(QRect(520, 310, 91, 141))
        self.btn_Substancia.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_Substancia.setPixmap(QPixmap(u":/icon/substancia.jpg"))
        self.btn_Substancia.setScaledContents(True)
        self.btn_Round_6 = QLabel(self.tela_principal_2)
        self.btn_Round_6.setObjectName(u"btn_Round_6")
        self.btn_Round_6.setGeometry(QRect(630, 310, 81, 141))
        self.btn_Round_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_Round_6.setPixmap(QPixmap(u":/icon/round 6.jpg"))
        self.btn_Round_6.setScaledContents(True)
        self.btn_Pousando_no_amor = QLabel(self.tela_principal_2)
        self.btn_Pousando_no_amor.setObjectName(u"btn_Pousando_no_amor")
        self.btn_Pousando_no_amor.setGeometry(QRect(730, 310, 91, 141))
        self.btn_Pousando_no_amor.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.btn_Pousando_no_amor.setPixmap(QPixmap(u":/icon/pousando no amor.jpg"))
        self.btn_Pousando_no_amor.setScaledContents(True)
        self.btn_Shop_For_killers = QLabel(self.tela_principal_2)
        self.btn_Shop_For_killers.setObjectName(u"btn_Shop_For_killers")
        self.btn_Shop_For_killers.setGeometry(QRect(840, 310, 81, 141))
        self.btn_Shop_For_killers.setPixmap(QPixmap(u":/icon/shop for killer.jpeg"))
        self.btn_Shop_For_killers.setScaledContents(True)
        self.btn_Duna_A_Profecia = QLabel(self.tela_principal_2)
        self.btn_Duna_A_Profecia.setObjectName(u"btn_Duna_A_Profecia")
        self.btn_Duna_A_Profecia.setGeometry(QRect(940, 310, 81, 141))
        self.btn_Duna_A_Profecia.setPixmap(QPixmap(u":/icon/duna serie.jpg"))
        self.btn_Duna_A_Profecia.setScaledContents(True)
        self.btn_O_Problema_dos_tres_corpos = QLabel(self.tela_principal_2)
        self.btn_O_Problema_dos_tres_corpos.setObjectName(u"btn_O_Problema_dos_tres_corpos")
        self.btn_O_Problema_dos_tres_corpos.setGeometry(QRect(940, 140, 81, 131))
        self.btn_O_Problema_dos_tres_corpos.setPixmap(QPixmap(u":/icon/O_Problema_dos_3_Corpos.webp"))
        self.btn_O_Problema_dos_tres_corpos.setScaledContents(True)
        self.txt_Populares = QLabel(self.tela_principal_2)
        self.txt_Populares.setObjectName(u"txt_Populares")
        self.txt_Populares.setGeometry(QRect(20, 100, 81, 16))
        self.txt_Populares.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe UI\";")

        self.retranslateUi(tela_principal_1)

        QMetaObject.connectSlotsByName(tela_principal_1)
    # setupUi

    def retranslateUi(self, tela_principal_1):
        tela_principal_1.setWindowTitle(QCoreApplication.translate("tela_principal_1", u"Form", None))
        self.btn_Cine_filme.setText(QCoreApplication.translate("tela_principal_1", u"CineFilmes", None))
        self.btn_icon_perfil.setText("")
        self.btn_Filmes_e_Series.setText(QCoreApplication.translate("tela_principal_1", u"Filmes e S\u00e9ries", None))
        self.btn_Recomendacao_aleatorio.setText(QCoreApplication.translate("tela_principal_1", u"Recomenda\u00e7\u00e3o aleat\u00f3rio", None))
        self.btn_Inicio.setText(QCoreApplication.translate("tela_principal_1", u"Inicio", None))
        self.btn_Star_wars.setText("")
        self.btn_Whicked.setText("")
        self.btn_Flow.setText("")
        self.btn_Ainda_estou_aqui.setText("")
        self.btn_Robo_Selvagem.setText("")
        self.btn_Avengers.setText("")
        self.btn_Diverdida_mente_2.setText("")
        self.btn_Jonh_Wick_3.setText("")
        self.btn_Duna_parte_2.setText("")
        self.btn_One_Piece_2.setText("")
        self.btn_Solteiro_em_seul.setText("")
        self.btn_ghost_in_the_shell.setText("")
        self.btn_Gladiador_2.setText("")
        self.btn_Senna.setText("")
        self.btn_Substancia.setText("")
        self.btn_Round_6.setText("")
        self.btn_Pousando_no_amor.setText("")
        self.btn_Shop_For_killers.setText("")
        self.btn_Duna_A_Profecia.setText("")
        self.btn_O_Problema_dos_tres_corpos.setText("")
        self.txt_Populares.setText(QCoreApplication.translate("tela_principal_1", u"Populares", None))
    # retranslateUi

import sys
from PySide6.QtWidgets import QApplication, QMainWindow
from tela_principal import Ui_tela_principal_1

if __name__ == "__main__":
    app = QApplication(sys.argv)
    Form = QMainWindow()
    ui = Ui_tela_principal_1()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())